### ISSUE TITLE
Determine QR Code Versions

### ISSUE THREAD

**Issue by NatanaelSK** [awesomejerry/react-native-qrcode-svg#128]
Hi. Thanks for your awesome package. I'm currently use your package to develop my app. Your package is working fine and it has no problem with generate QR Code. But, when i tried to scan the QR Code that generated from your package using ESP32 CAM, it shows nothing while the other QR Code that generated from website and apps are working fine with my ESP32 CAM. Then i figured out that the QR Code from your package are using version 2 (where it using 25 modules) while the QR Code from website are using version 1 (where it using 21 modules). So, is there a way i can change the QR Code version? Thanks and sorry for my bad english.

**Comment by awesomejerry** [comment]
Hi, if you're still interested, I think the best way is to add a `prop` called `version` and pass it to `genMatrix` since [`qrcode`](https://www.npmjs.com/package/qrcode) provides this [option](https://www.npmjs.com/package/qrcode#qr-code-options). You can submit a PR and I'll just merge and release.
