### ISSUE TITLE
Value other than string

### ISSUE THREAD

**Issue by amiburch** [awesomejerry/react-native-qrcode-svg#38]
Hi there,
I'm trying to pass an API POST endpoint with the body as an async function into the value
`value={this.postData()}`
I keep getting an error back. Is there a way to do what I'm trying to do? I'm ultimately using the QR code to send that API request when the code is scanned.

**Comment by awesomejerry** [comment]
All QR code store is a string (the value of `<QRCode>`). It's impossible to pass an async function to the component.

As for what you want to do, the possible ways of doing that is modifying the POST endpoint to a GET one, so that when the QR code is scanned, your endpoint will be triggered. The other should be modifying your app's scanning callback (such as `onBarCodeRead` in `react-native-camera`) to make that request when the corresponding QR code is being scanned.

I'm closing this issue cuz it seems not relevant to this library. Feel free to re-open and discuss more!
