### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by DomiR** [awesomejerry/react-native-qrcode-svg#91]
First of all, thank you for this project!

Are you releasing this project according to semver? Could you please add a Changelog.md and explain breaking changes or add releases in the releases tab?

Thanks!

**Comment by awesomejerry** [comment]
Hi, sorry for the late reply. Having spending my time on other projects recently. Currently this project is released based on my personal style. It's a little bit like semantic versioning(major/minor/patch), but not strictly stick to it.
The `changelog.md` is bit difficult for me to maintain right now. This project should be stable and simple as it is, so maybe a `changelog.md` is not necessary :D.
I'll try to use the releases tab instead though!

**Comment by flogy** [comment]
@awesomejerry first of all, thanks for the awesome library!

I am confused by the missing `changelog.md` / the missing latest GitHub releases as well, which is why I landed here. If I understand your answer correctly we can always assume there are no breaking changes, even though if there was a major version increase, right? Or how would you communicate if there was a breaking change?

Thanks in advance.

**Comment by awesomejerry** [comment]
There shouldn't be any breaking changes once it's stable considering it's a really simple library. However, if there is any PRs or changes that breaks things in the future, I think I'll just put some note on GitHub release description.

Sorry for not updating GitHub releases. I just forgot it when I made the release :)
